/* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms. */

// Creating the Fibbonaci list (last nr < 4.000.000)
function FibList() {
  var Fibbonaci = [1, 2];
  var i = 1;
  var nr = 0;
  while (nr < 4000000) {
    nr = Fibbonaci[i] + Fibbonaci[i-1];
    i = i + 1;
    Fibbonaci.push(nr);
  }
  Fibbonaci.pop();
  return Fibbonaci;
}

// Returning the sum of even numbers from the list
function sumOfEven() {
  var suma = 0;
  for (var i = 0; i < FibList().length; i++) {
    if (FibList()[i] % 2 === 0) {
      suma = suma + FibList()[i];
    }
  }
  return suma;
}

console.log(sumOfEven());
